spring:
  web:
    resources:
      add-mappings: false

  application:
    name: planb

  # DB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
        format_sql: true

  # Redis
  data:
    redis:
      host: localhost
      port: 6379

security:
  jwt:
    prefix: 'Bearer '
    access-token-header: Authorization
    refresh-token-header: AuthorizationRefresh
    secret-key: ${JWT_SECRET_KEY}
    access-token-TTL: 1800 # 30분
    refresh-token-TTL: 259200